### ISSUE TITLE
Composer dependency

### ISSUE THREAD

**Issue by s3rgiosan** [julien731/WP-Dismissible-Notices-Handler#2]
Hi,

How I can use your library as a composer managed dependency on a project?

I've installed it with the command `composer require julien731/wp-dismissible-notices-handler=dev-master` but when I try to use the `dnh_register_notice` function I get a `PHP Fatal error:  Call to undefined function dnh_register_notice()`.

What I'm doing wrong?

Regards

**Comment by julien731** [comment]
Hi @s3rgiosan ,

After you required the library as a Composer package, how do you load it? Do you use the Composer autoloader or are you loading it manually?

**Comment by s3rgiosan** [comment]
Hi @julien731, I'm using the composer autoloader.

The `autoload_classmap.php` and the `autoload_files.php` doesn't have any reference to your files or classes.

**Comment by julien731** [comment]
Hey @s3rgiosan sorry about that. The library was indeed not autoloaded. I just pushed an update that fixes it. I didn't test it though, feedback welcome ;)

**Comment by s3rgiosan** [comment]
Hi @julien731, thanks for the update.

I've made the exact same change on my fork a week ago and i've been using it like that without any issues.
